### ISSUE TITLE
A small problem with installing

### ISSUE THREAD

**Issue by inyutin** [ChrisKnott/Algojammer#16]
When I tried to run algojammer.py, I got an error:

Traceback (most recent call last):
  File "algojammer.py", line 1, in <module>
    import eel, state_boxes as sbx, execution as exe, state as sta, time as tme
  File "/home/dmitry/Code/Algojammer/state_boxes.py", line 2, in <module>
    import tkinter as tkt, tkinter.filedialog as fdg
  File "/usr/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

It easily fixed by installing "tkinter" package. Probably you should specify it in README.

**Comment by ChrisKnott** [comment]
Tkinter is part of stdlib though, or so I thought...

**Comment by inyutin** [comment]
Yeah, it suppose to be. I think it may relate to Arch OS.
